name = "meetup-announcebot"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 */2 * * *"]

[[kv_namespaces]]
binding = "HISTORY_KV"
id = "3761b04a7863402c96b68b80e3a9b40b"

[vars]
MEETUP_NAME = "uptown-nyc-board-gamers"
LEAD_TIME_DAYS = "6.5"
# FAKE_SEND = "y"
