name = "meetup-announcebot"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 */2 * * *"]

[[kv_namespaces]]
binding = "HISTORY_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"

[vars]
MEETUP_NAME = "My-Gaming-Meetup"
LEAD_TIME_DAYS = "6.5"
# FAKE_SEND = "y"
